name: Capture M3U8 + M3U

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        playwright install

    - name: Ejecutar script
      run: python capture.py

    - name: Subir lista M3U
      uses: actions/upload-artifact@v3
      with:
        name: lista-m3u
        path: lista.m3u
